name: Test

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 22 * * 3'
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: Test
    strategy:
      matrix:
        node-version:
          - '20.19'
          - '18.18'
          - '16.20'
          - '14.21'
        os:
          - ubuntu-22.04
          - windows-latest
    runs-on: "${{ matrix.os }}"
    env:
      WINEDLLOVERRIDES: mscoree,mshtml=
      WINEDEBUG: -all
    steps:
      - name: Install Dependencies (Linux)
        if : ${{ matrix.os == 'ubuntu-22.04' }}
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get -qq update
          sudo apt-get install --no-install-recommends -y wine64 wine32 wine mono-devel
          wine64 hostname
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: "${{ matrix.node-version }}"
          cache: 'yarn'
      - name: Install (Node.js v16+)
        if : ${{ matrix.node-version != '14.21' }}
        run: yarn install --frozen-lockfile
      - name: Install (Node.js v14)
        if : ${{ matrix.node-version == '14.21' }}
        run: yarn install --frozen-lockfile --ignore-engines
      - name: Test
        run: yarn test
